### ISSUE TITLE
[Speaker profile page] The portrait picture is not exactly 1:1 

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#105]
The pictures of speaker show just fine on the Speaker page. But in the single speaker's profile page, the portrait is not exactly 1:1 and will be cropped. 

Should just keep the 1:1 ratio.

**Comment by arch-jslin** [comment]
Is there absolutely no way to change it? If we can just edit some CSS and fix it, I would still prefer we fix this. 

But sure, the priority of this is not high.

**Comment by elct9620** [comment]
If we want 1:1, it should change the uploader to ensure our program will crop it using 1:1. I can change it to use 1:1 if we have any reason we need it, ex. all speaker submit their picture using 1:1 ratio.

**Comment by arch-jslin** [comment]
Yes, we have been asking all speakers to give us 1:1 portrait pictures from the beginning. 

All the speaker pictures I currently uploaded are 1:1.

**Comment by elct9620** [comment]
Ok, I will update the program to use 1:1 ratio.
