### ISSUE TITLE
[Production site / Agenda page] time's column is too narrow (or time's text need a linebreak?)

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#162]
![image](https://user-images.githubusercontent.com/16171/43760176-eb2d78be-9a53-11e8-99c1-cedc3c79e2bd.png)

I haven't noticed this a few days ago. Just check the site today and it's broken.

**Comment by elct9620** [comment]
@yanglin5689446 改 #160 的時候又把這邊改壞了 :joy:
