### ISSUE TITLE
[Agenda Page] translation tag on the Agenda 

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#171]
Need to add small icon or tag for each session on Agenda. 

Need to consider both viewing under Chinese setting or under English setting. 

And we actually have to discuss what kinds of tags do we need, for example:
- when viewing in Chinese: 
-- [同步口譯] [逐句口譯] [簡報翻譯] 

- when viewing in English: 
-- [EN] [ZH] [JP]  

You'll notice my suggestion is not the same for Chinese viewer or English viewer; because: 
- The majority of the sessions will be Chinese-only for the forseeable future.
- People who is not speaking in Chinese will use the English page. (so can't only just consider English users)  
- But for Chinese speaking users, the only thing they are interested in is "if this is a foreign speaker, will I be able to understand it in Chinese" 

So, for a non-Chinese user to see a translated English speaker session, they will see [EN] [ZH] tags, but for a Chinese user to see the same session, they might see either one of [同步口譯] or [逐句口譯] or [簡報翻譯].  

If possible, also incorporate this into Speaker's Profile page.

**Comment by elct9620** [comment]
#184 add support for `tag` feature for agenda

**Comment by arch-jslin** [comment]
I need a checkbox in Tag objects to identify which languages I don't want the tag to show

**Comment by arch-jslin** [comment]
e.g. [同步口譯] or [逐句口譯] or [簡報翻譯] < I don't want these to show on English page
        [EN] [ZH] [JP] < I don't want these to show on Traditional Chinese page
