### ISSUE TITLE
[Agenda Page] We need a "Category" tag for sessions on Agenda 

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#172]
Current category: 

*important* can be multiple choices
遊戲設計 / Game Design
程式 / Programming
視覺 / Visual Arts
音樂音效 / Audio
製程與管理 / Production & Management
行銷與商務 / Marketing & Business
非數位 / Non-Digital 
各式實境 / XR  
其他 / Other

If possible, also incorporate this into Speaker's Profile page.

**Comment by elct9620** [comment]
#184 add `tag` support for agenda
