### ISSUE TITLE
[Speaker Profile Page] If the associated Agenda item is only 30mins, it will still show an hour slot.

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#213]
I am writing this off for future enhancement, but "technically" we now DO NOT have "Time" info in half-hour (30mins) format -- everything must be in a full-hour (60mins) -- this makes sense on the Agenda multi-track view, but in Speaker Profile Page this may be confusing. 

![image](https://user-images.githubusercontent.com/16171/55707951-5a76e600-5a17-11e9-9fe6-0074e5cac968.png)

**Comment by elct9620** [comment]
I will add the `begin_at` and `end_at` fields to override the default time slot.

Priority:

Agenda's time > Time slot's label
