### ISSUE TITLE
Indie Space description cannot translated to English

### ISSUE THREAD

**Issue by elct9620** [TGDF/official-site#449]
As title, after upgrade Mobility gem the translate feature for Indie Space description is broken for now.

**Comment by arch-jslin** [comment]
Sponsor page's translation module seems to work fine

**Comment by arch-jslin** [comment]
Related issue: we still need the rich-text block for the nightmarket page

**Comment by arch-jslin** [comment]
The rich-text Blocks functionality's appearance hasn't been added yet.

**Comment by arch-jslin** [comment]
This is an old issue that should've been resolved on the live site. The CSS differences between the staging and live site now (as of 2022.12) isn't related to this. Closing.
