### ISSUE TITLE
Numbered list in article doesn't show the numbers 

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#74]
Not sure if this is the same CSS issue with white texts. 

image: https://imgur.com/a/CF0Ty

Checked the page source, and it does render \<ol> and \<li> correctly, but the numbered list's numbers doesn't show.

**Comment by elct9620** [comment]
Same problem #73, this theme is not well designed. Anyway, I will add monkey patch in this year, and plan to new design for next year.
