### ISSUE TITLE
"Figure" image uploading for site generates error

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#77]
"translation missing: zh-TW.errors.messages.extension_whitelist_error"

Of course this is not a translation error I assume. But I have no idea what "extension_whitelist_error" could be. 

Anyway the front page image uploading doesn't work as of now. 

screenshot: https://imgur.com/a/ZH5Ep

**Comment by elct9620** [comment]
The images only support `.png` `.jpg` type, if the file extension is not correct, this error will be shown.

**Comment by arch-jslin** [comment]
No, I am uploading a plain jpg.

**Comment by elct9620** [comment]
Update:

Current the FigureUploader didn't allow `jpg` extension, I take a mistake for that.
