### ISSUE TITLE
"Buy Ticket" button on the nav bar need a more robust hyperlink

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#89]
Currently the button will only work on Home, because it points to relative path "/#ticket-section" -- this will not be the case when you are at https://2018.tgdf.tw/news/ or other pages. (Will be pointing to https://2018.tgdf.tw/news/#ticket-section due to relative path.)

**Comment by elct9620** [comment]
It looks current theme didn't design for that. I suggest we direct set the target to registration page instead jump to the home page buy ticket section.
