### ISSUE TITLE
[Urgent] Speaker info page needed very soon -- also need to be bilingual 

### ISSUE THREAD

**Issue by arch-jslin** [TGDF/official-site#98]
Preferably before May 28th. 

I've uploaded the 5 speakers whose personal pictures we've already got and their corresponding bio and talk synopsis using the Speaker and Agenda upload form. These can be used as test data. 

But the upload form doesn't have English / Traditional Chinese tabs just yet, so we currently doesn't have localization options here.

**Comment by elct9620** [comment]
Create new speaker are default using Chinese. But after created, we can edit other language versions.

Note: The updated speaker display feature need to upload to let it resize to correct size.
